# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml.
# All the settings in this file will be loaded at Dancer's startup.

server_tokens: 0
require_environment: 1
session_name: perldance.session
conference_name: "Perl Dancer Conference 2015"

geoip_database:
  city: /usr/share/GeoIP/GeoLiteCity.dat
  country4: /usr/share/GeoIP/GeoIP.dat
  country6: /usr/share/GeoIP/GeoIPv6.dat

# Your application's name
appname: "PerlDance"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# When the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# include timestamp in log format
logger_format: "%t [%P] %L @%D> %m in %f l. %l"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

template: "template_flute"

engines:
  template_flute:
    filters:
      boolean:
        class: "PerlDance::Filter::Boolean"
      currency:
        options:
          int_curr_symbol: "€"
      date:
        class: "Template::Flute::Filter::Date"
        options:
          format: '%x %R'
          strict:
            empty: 0
      date_only:
        class: "Template::Flute::Filter::Date"
        options:
          format: '%x'
          strict:
            empty: 0
      markdown:
        class: "PerlDance::Filter::Markdown"
      markdown_unsafe:
        class: "PerlDance::Filter::Markdown"
        options:
          unsafe: 1
      time_only:
        class: "Template::Flute::Filter::Date"
        options:
          format: '%R'
          strict:
            empty: 0
plugins:
  Auth::Extensible:
    disable_roles: 0
    exit_page: '/'
    no_login_handler: 1
    login_page: /login
    logout_page: /logout
    denied_page: /login/denied
    no_default_pages: 1
    no_api_change_warning: 1
    realms:
      users:
        provider: 'DBIC'
        db_connection_name: 'default'
        users_resultset: User
        roles_relationship: roles
        role_column: name
        username_column: username
        password_column: password
        password_check: check_password
  DBIC:
    default:
      dsn: dbi:Pg:dbname=perldance
      schema_class: PerlDance::Schema
      options:
        RaiseError: 1
        PrintError: 1
        on_connect_do: 'SET client_min_messages=WARNING;'
        pg_enable_utf8: 1
        quote_names: 1
  Email:
    headers:
      sender: "2015@perl.dance"
      from: "Perl Dancer 2015 <2015@perl.dance>"
      to: "Perl Dancer 2015 <2015@perl.dance>"
      X-Mailer: "PerlDance2015 1.0"
  FlashNote:
    queue: key_multiple
    arguments: single
    dequeue: never
  Interchange6::Routes:
    navigation:
      template: product-listing
      default_view: list
      records: 10
    product:
      template: product-page
    account:
      login:
        template: sign-in
checkout_type: multi
